[package]
name = "gixl"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.42", features = ["derive"] }
crossterm = "0.29.0"
gix = { version = "0.73.0" }
ratatui = "0.29.0"
color-eyre = "0.6.5"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
